<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
<script>
    //catch可以捕获错误信息
    //finally  不管是成功还是失败都要执行的代码，我们可以放到这个函数中
    //then  catch  finally  这个三个方法都是在promise的原型上
    //all  race  resolve   reject
let p=new Promise(function(res,rej){

})

var p1= new Promise(function (res,rej){
    setTimeout(()=>{
        rej(111)
    },2000)
})

var p2= new Promise(function (res,rej){
    setTimeout(()=>{
        rej(222)
    },3000)
})

var p3= new Promise(function (res,rej){
    setTimeout(()=>{
        res(333)
    },4000)
})

//所有都成功，才会走成功的函数，只要有一个失败，就会直接走对应的失败函数
//executor 函数是一个同步执行的函数，then  catch 里边的函数式是异步执行的
Promise.all([p1,p2,p3]).then((data)=>{
    console.log(data);
    
},(err)=>{
    console.log('err',err);
    
});
Promise.allSettled([p1,p2,p3]).then((data)=>{
        console.log(data)
    });

    Promise.race([p1,p2,p3]).then((data)=>{
        console.log('success',data);
        
    },(err)=>{
        console.log('fail',err);
        
    })

 Promise.resolve(123).then((data)=>{
     console.log(data);
     
 });
 Promise.reject(444).then((data)=>{
     console.log(data);
     
 }).catch((er)=>{
     console.log(err);
     
 })
</script>